/* eslint-disable */
// This client was generated by Platformatic from an OpenAPI specification.

import type { GeneratedApi } from './generated-api-types'
import type * as Types from './generated-api-types'

// The base URL for the API. This can be overridden by calling `setBaseUrl`.
let baseUrl = ''
// The default headers to send within each request. This can be overridden by calling `setDefaultHeaders`.
let defaultHeaders = {}
// The additional parameters you want to pass to the `fetch` instance.
let defaultFetchParams = {}
const defaultJsonType = { 'Content-type': 'application/json; charset=utf-8' }

function sanitizeUrl(url: string) : string {
  if (url.endsWith('/')) { return url.slice(0, -1) } else { return url }
}
export const setBaseUrl = (newUrl: string) : void => { baseUrl = sanitizeUrl(newUrl) }

export const setDefaultHeaders = (headers: object): void => { defaultHeaders = headers }

export const setDefaultFetchParams = (fetchParams: RequestInit): void => { defaultFetchParams = fetchParams }

type JSON = Record<string, unknown>
/* @ts-ignore - potential unused variable */
function headersToJSON(headers: Headers): JSON {
  const output: JSON = {}
  headers.forEach((value, key) => {
    output[key] = value
  })
  return output
}

const _instrumentsServiceBondBy = async (url: string, request: Types.InstrumentsServiceBondByRequest): Promise<Types.InstrumentsServiceBondByResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/BondBy`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceBondBy: GeneratedApi['instrumentsServiceBondBy'] = async (request: Types.InstrumentsServiceBondByRequest): Promise<Types.InstrumentsServiceBondByResponses> => {
  return await _instrumentsServiceBondBy(baseUrl, request)
}
const _instrumentsServiceBonds = async (url: string, request: Types.InstrumentsServiceBondsRequest): Promise<Types.InstrumentsServiceBondsResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/Bonds`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceBonds: GeneratedApi['instrumentsServiceBonds'] = async (request: Types.InstrumentsServiceBondsRequest): Promise<Types.InstrumentsServiceBondsResponses> => {
  return await _instrumentsServiceBonds(baseUrl, request)
}
const _instrumentsServiceCurrencies = async (url: string, request: Types.InstrumentsServiceCurrenciesRequest): Promise<Types.InstrumentsServiceCurrenciesResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/Currencies`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceCurrencies: GeneratedApi['instrumentsServiceCurrencies'] = async (request: Types.InstrumentsServiceCurrenciesRequest): Promise<Types.InstrumentsServiceCurrenciesResponses> => {
  return await _instrumentsServiceCurrencies(baseUrl, request)
}
const _instrumentsServiceCurrencyBy = async (url: string, request: Types.InstrumentsServiceCurrencyByRequest): Promise<Types.InstrumentsServiceCurrencyByResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/CurrencyBy`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceCurrencyBy: GeneratedApi['instrumentsServiceCurrencyBy'] = async (request: Types.InstrumentsServiceCurrencyByRequest): Promise<Types.InstrumentsServiceCurrencyByResponses> => {
  return await _instrumentsServiceCurrencyBy(baseUrl, request)
}
const _instrumentsServiceEditFavorites = async (url: string, request: Types.InstrumentsServiceEditFavoritesRequest): Promise<Types.InstrumentsServiceEditFavoritesResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/EditFavorites`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceEditFavorites: GeneratedApi['instrumentsServiceEditFavorites'] = async (request: Types.InstrumentsServiceEditFavoritesRequest): Promise<Types.InstrumentsServiceEditFavoritesResponses> => {
  return await _instrumentsServiceEditFavorites(baseUrl, request)
}
const _instrumentsServiceEtfBy = async (url: string, request: Types.InstrumentsServiceEtfByRequest): Promise<Types.InstrumentsServiceEtfByResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/EtfBy`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceEtfBy: GeneratedApi['instrumentsServiceEtfBy'] = async (request: Types.InstrumentsServiceEtfByRequest): Promise<Types.InstrumentsServiceEtfByResponses> => {
  return await _instrumentsServiceEtfBy(baseUrl, request)
}
const _instrumentsServiceEtfs = async (url: string, request: Types.InstrumentsServiceEtfsRequest): Promise<Types.InstrumentsServiceEtfsResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/Etfs`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceEtfs: GeneratedApi['instrumentsServiceEtfs'] = async (request: Types.InstrumentsServiceEtfsRequest): Promise<Types.InstrumentsServiceEtfsResponses> => {
  return await _instrumentsServiceEtfs(baseUrl, request)
}
const _instrumentsServiceFindInstrument = async (url: string, request: Types.InstrumentsServiceFindInstrumentRequest): Promise<Types.InstrumentsServiceFindInstrumentResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/FindInstrument`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceFindInstrument: GeneratedApi['instrumentsServiceFindInstrument'] = async (request: Types.InstrumentsServiceFindInstrumentRequest): Promise<Types.InstrumentsServiceFindInstrumentResponses> => {
  return await _instrumentsServiceFindInstrument(baseUrl, request)
}
const _instrumentsServiceFutureBy = async (url: string, request: Types.InstrumentsServiceFutureByRequest): Promise<Types.InstrumentsServiceFutureByResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/FutureBy`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceFutureBy: GeneratedApi['instrumentsServiceFutureBy'] = async (request: Types.InstrumentsServiceFutureByRequest): Promise<Types.InstrumentsServiceFutureByResponses> => {
  return await _instrumentsServiceFutureBy(baseUrl, request)
}
const _instrumentsServiceFutures = async (url: string, request: Types.InstrumentsServiceFuturesRequest): Promise<Types.InstrumentsServiceFuturesResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/Futures`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceFutures: GeneratedApi['instrumentsServiceFutures'] = async (request: Types.InstrumentsServiceFuturesRequest): Promise<Types.InstrumentsServiceFuturesResponses> => {
  return await _instrumentsServiceFutures(baseUrl, request)
}
const _instrumentsServiceGetAccruedInterests = async (url: string, request: Types.InstrumentsServiceGetAccruedInterestsRequest): Promise<Types.InstrumentsServiceGetAccruedInterestsResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetAccruedInterests`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceGetAccruedInterests: GeneratedApi['instrumentsServiceGetAccruedInterests'] = async (request: Types.InstrumentsServiceGetAccruedInterestsRequest): Promise<Types.InstrumentsServiceGetAccruedInterestsResponses> => {
  return await _instrumentsServiceGetAccruedInterests(baseUrl, request)
}
const _instrumentsServiceGetAssetBy = async (url: string, request: Types.InstrumentsServiceGetAssetByRequest): Promise<Types.InstrumentsServiceGetAssetByResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetAssetBy`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceGetAssetBy: GeneratedApi['instrumentsServiceGetAssetBy'] = async (request: Types.InstrumentsServiceGetAssetByRequest): Promise<Types.InstrumentsServiceGetAssetByResponses> => {
  return await _instrumentsServiceGetAssetBy(baseUrl, request)
}
const _instrumentsServiceGetAssets = async (url: string, request: Types.InstrumentsServiceGetAssetsRequest): Promise<Types.InstrumentsServiceGetAssetsResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetAssets`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceGetAssets: GeneratedApi['instrumentsServiceGetAssets'] = async (request: Types.InstrumentsServiceGetAssetsRequest): Promise<Types.InstrumentsServiceGetAssetsResponses> => {
  return await _instrumentsServiceGetAssets(baseUrl, request)
}
const _instrumentsServiceGetBondCoupons = async (url: string, request: Types.InstrumentsServiceGetBondCouponsRequest): Promise<Types.InstrumentsServiceGetBondCouponsResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetBondCoupons`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceGetBondCoupons: GeneratedApi['instrumentsServiceGetBondCoupons'] = async (request: Types.InstrumentsServiceGetBondCouponsRequest): Promise<Types.InstrumentsServiceGetBondCouponsResponses> => {
  return await _instrumentsServiceGetBondCoupons(baseUrl, request)
}
const _instrumentsServiceGetBrandBy = async (url: string, request: Types.InstrumentsServiceGetBrandByRequest): Promise<Types.InstrumentsServiceGetBrandByResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetBrandBy`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceGetBrandBy: GeneratedApi['instrumentsServiceGetBrandBy'] = async (request: Types.InstrumentsServiceGetBrandByRequest): Promise<Types.InstrumentsServiceGetBrandByResponses> => {
  return await _instrumentsServiceGetBrandBy(baseUrl, request)
}
const _instrumentsServiceGetBrands = async (url: string, request: Types.InstrumentsServiceGetBrandsRequest): Promise<Types.InstrumentsServiceGetBrandsResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetBrands`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceGetBrands: GeneratedApi['instrumentsServiceGetBrands'] = async (request: Types.InstrumentsServiceGetBrandsRequest): Promise<Types.InstrumentsServiceGetBrandsResponses> => {
  return await _instrumentsServiceGetBrands(baseUrl, request)
}
const _instrumentsServiceGetCountries = async (url: string, request: Types.InstrumentsServiceGetCountriesRequest): Promise<Types.InstrumentsServiceGetCountriesResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetCountries`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceGetCountries: GeneratedApi['instrumentsServiceGetCountries'] = async (request: Types.InstrumentsServiceGetCountriesRequest): Promise<Types.InstrumentsServiceGetCountriesResponses> => {
  return await _instrumentsServiceGetCountries(baseUrl, request)
}
const _instrumentsServiceGetDividends = async (url: string, request: Types.InstrumentsServiceGetDividendsRequest): Promise<Types.InstrumentsServiceGetDividendsResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetDividends`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceGetDividends: GeneratedApi['instrumentsServiceGetDividends'] = async (request: Types.InstrumentsServiceGetDividendsRequest): Promise<Types.InstrumentsServiceGetDividendsResponses> => {
  return await _instrumentsServiceGetDividends(baseUrl, request)
}
const _instrumentsServiceGetFavorites = async (url: string, request: Types.InstrumentsServiceGetFavoritesRequest): Promise<Types.InstrumentsServiceGetFavoritesResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetFavorites`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceGetFavorites: GeneratedApi['instrumentsServiceGetFavorites'] = async (request: Types.InstrumentsServiceGetFavoritesRequest): Promise<Types.InstrumentsServiceGetFavoritesResponses> => {
  return await _instrumentsServiceGetFavorites(baseUrl, request)
}
const _instrumentsServiceGetFuturesMargin = async (url: string, request: Types.InstrumentsServiceGetFuturesMarginRequest): Promise<Types.InstrumentsServiceGetFuturesMarginResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetFuturesMargin`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceGetFuturesMargin: GeneratedApi['instrumentsServiceGetFuturesMargin'] = async (request: Types.InstrumentsServiceGetFuturesMarginRequest): Promise<Types.InstrumentsServiceGetFuturesMarginResponses> => {
  return await _instrumentsServiceGetFuturesMargin(baseUrl, request)
}
const _instrumentsServiceGetInstrumentBy = async (url: string, request: Types.InstrumentsServiceGetInstrumentByRequest): Promise<Types.InstrumentsServiceGetInstrumentByResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetInstrumentBy`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceGetInstrumentBy: GeneratedApi['instrumentsServiceGetInstrumentBy'] = async (request: Types.InstrumentsServiceGetInstrumentByRequest): Promise<Types.InstrumentsServiceGetInstrumentByResponses> => {
  return await _instrumentsServiceGetInstrumentBy(baseUrl, request)
}
const _instrumentsServiceOptionBy = async (url: string, request: Types.InstrumentsServiceOptionByRequest): Promise<Types.InstrumentsServiceOptionByResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/OptionBy`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceOptionBy: GeneratedApi['instrumentsServiceOptionBy'] = async (request: Types.InstrumentsServiceOptionByRequest): Promise<Types.InstrumentsServiceOptionByResponses> => {
  return await _instrumentsServiceOptionBy(baseUrl, request)
}
const _instrumentsServiceOptions = async (url: string, request: Types.InstrumentsServiceOptionsRequest): Promise<Types.InstrumentsServiceOptionsResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/Options`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceOptions: GeneratedApi['instrumentsServiceOptions'] = async (request: Types.InstrumentsServiceOptionsRequest): Promise<Types.InstrumentsServiceOptionsResponses> => {
  return await _instrumentsServiceOptions(baseUrl, request)
}
const _instrumentsServiceOptionsBy = async (url: string, request: Types.InstrumentsServiceOptionsByRequest): Promise<Types.InstrumentsServiceOptionsByResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/OptionsBy`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceOptionsBy: GeneratedApi['instrumentsServiceOptionsBy'] = async (request: Types.InstrumentsServiceOptionsByRequest): Promise<Types.InstrumentsServiceOptionsByResponses> => {
  return await _instrumentsServiceOptionsBy(baseUrl, request)
}
const _instrumentsServiceShareBy = async (url: string, request: Types.InstrumentsServiceShareByRequest): Promise<Types.InstrumentsServiceShareByResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/ShareBy`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceShareBy: GeneratedApi['instrumentsServiceShareBy'] = async (request: Types.InstrumentsServiceShareByRequest): Promise<Types.InstrumentsServiceShareByResponses> => {
  return await _instrumentsServiceShareBy(baseUrl, request)
}
const _instrumentsServiceShares = async (url: string, request: Types.InstrumentsServiceSharesRequest): Promise<Types.InstrumentsServiceSharesResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/Shares`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceShares: GeneratedApi['instrumentsServiceShares'] = async (request: Types.InstrumentsServiceSharesRequest): Promise<Types.InstrumentsServiceSharesResponses> => {
  return await _instrumentsServiceShares(baseUrl, request)
}
const _instrumentsServiceTradingSchedules = async (url: string, request: Types.InstrumentsServiceTradingSchedulesRequest): Promise<Types.InstrumentsServiceTradingSchedulesResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.InstrumentsService/TradingSchedules`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const instrumentsServiceTradingSchedules: GeneratedApi['instrumentsServiceTradingSchedules'] = async (request: Types.InstrumentsServiceTradingSchedulesRequest): Promise<Types.InstrumentsServiceTradingSchedulesResponses> => {
  return await _instrumentsServiceTradingSchedules(baseUrl, request)
}
const _marketDataServiceGetCandles = async (url: string, request: Types.MarketDataServiceGetCandlesRequest): Promise<Types.MarketDataServiceGetCandlesResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.MarketDataService/GetCandles`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const marketDataServiceGetCandles: GeneratedApi['marketDataServiceGetCandles'] = async (request: Types.MarketDataServiceGetCandlesRequest): Promise<Types.MarketDataServiceGetCandlesResponses> => {
  return await _marketDataServiceGetCandles(baseUrl, request)
}
const _marketDataServiceGetClosePrices = async (url: string, request: Types.MarketDataServiceGetClosePricesRequest): Promise<Types.MarketDataServiceGetClosePricesResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.MarketDataService/GetClosePrices`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const marketDataServiceGetClosePrices: GeneratedApi['marketDataServiceGetClosePrices'] = async (request: Types.MarketDataServiceGetClosePricesRequest): Promise<Types.MarketDataServiceGetClosePricesResponses> => {
  return await _marketDataServiceGetClosePrices(baseUrl, request)
}
const _marketDataServiceGetLastPrices = async (url: string, request: Types.MarketDataServiceGetLastPricesRequest): Promise<Types.MarketDataServiceGetLastPricesResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.MarketDataService/GetLastPrices`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const marketDataServiceGetLastPrices: GeneratedApi['marketDataServiceGetLastPrices'] = async (request: Types.MarketDataServiceGetLastPricesRequest): Promise<Types.MarketDataServiceGetLastPricesResponses> => {
  return await _marketDataServiceGetLastPrices(baseUrl, request)
}
const _marketDataServiceGetLastTrades = async (url: string, request: Types.MarketDataServiceGetLastTradesRequest): Promise<Types.MarketDataServiceGetLastTradesResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.MarketDataService/GetLastTrades`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const marketDataServiceGetLastTrades: GeneratedApi['marketDataServiceGetLastTrades'] = async (request: Types.MarketDataServiceGetLastTradesRequest): Promise<Types.MarketDataServiceGetLastTradesResponses> => {
  return await _marketDataServiceGetLastTrades(baseUrl, request)
}
const _marketDataServiceGetOrderBook = async (url: string, request: Types.MarketDataServiceGetOrderBookRequest): Promise<Types.MarketDataServiceGetOrderBookResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.MarketDataService/GetOrderBook`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const marketDataServiceGetOrderBook: GeneratedApi['marketDataServiceGetOrderBook'] = async (request: Types.MarketDataServiceGetOrderBookRequest): Promise<Types.MarketDataServiceGetOrderBookResponses> => {
  return await _marketDataServiceGetOrderBook(baseUrl, request)
}
const _marketDataServiceGetTradingStatus = async (url: string, request: Types.MarketDataServiceGetTradingStatusRequest): Promise<Types.MarketDataServiceGetTradingStatusResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.MarketDataService/GetTradingStatus`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const marketDataServiceGetTradingStatus: GeneratedApi['marketDataServiceGetTradingStatus'] = async (request: Types.MarketDataServiceGetTradingStatusRequest): Promise<Types.MarketDataServiceGetTradingStatusResponses> => {
  return await _marketDataServiceGetTradingStatus(baseUrl, request)
}
const _marketDataServiceGetTradingStatuses = async (url: string, request: Types.MarketDataServiceGetTradingStatusesRequest): Promise<Types.MarketDataServiceGetTradingStatusesResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.MarketDataService/GetTradingStatuses`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const marketDataServiceGetTradingStatuses: GeneratedApi['marketDataServiceGetTradingStatuses'] = async (request: Types.MarketDataServiceGetTradingStatusesRequest): Promise<Types.MarketDataServiceGetTradingStatusesResponses> => {
  return await _marketDataServiceGetTradingStatuses(baseUrl, request)
}
const _marketDataStreamServiceMarketDataServerSideStream = async (url: string, request: Types.MarketDataStreamServiceMarketDataServerSideStreamRequest): Promise<Types.MarketDataStreamServiceMarketDataServerSideStreamResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.MarketDataStreamService/MarketDataServerSideStream`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const marketDataStreamServiceMarketDataServerSideStream: GeneratedApi['marketDataStreamServiceMarketDataServerSideStream'] = async (request: Types.MarketDataStreamServiceMarketDataServerSideStreamRequest): Promise<Types.MarketDataStreamServiceMarketDataServerSideStreamResponses> => {
  return await _marketDataStreamServiceMarketDataServerSideStream(baseUrl, request)
}
const _marketDataStreamServiceMarketDataStream = async (url: string, request: Types.MarketDataStreamServiceMarketDataStreamRequest): Promise<Types.MarketDataStreamServiceMarketDataStreamResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.MarketDataStreamService/MarketDataStream`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const marketDataStreamServiceMarketDataStream: GeneratedApi['marketDataStreamServiceMarketDataStream'] = async (request: Types.MarketDataStreamServiceMarketDataStreamRequest): Promise<Types.MarketDataStreamServiceMarketDataStreamResponses> => {
  return await _marketDataStreamServiceMarketDataStream(baseUrl, request)
}
const _operationsServiceGetBrokerReport = async (url: string, request: Types.OperationsServiceGetBrokerReportRequest): Promise<Types.OperationsServiceGetBrokerReportResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.OperationsService/GetBrokerReport`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const operationsServiceGetBrokerReport: GeneratedApi['operationsServiceGetBrokerReport'] = async (request: Types.OperationsServiceGetBrokerReportRequest): Promise<Types.OperationsServiceGetBrokerReportResponses> => {
  return await _operationsServiceGetBrokerReport(baseUrl, request)
}
const _operationsServiceGetDividendsForeignIssuer = async (url: string, request: Types.OperationsServiceGetDividendsForeignIssuerRequest): Promise<Types.OperationsServiceGetDividendsForeignIssuerResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.OperationsService/GetDividendsForeignIssuer`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const operationsServiceGetDividendsForeignIssuer: GeneratedApi['operationsServiceGetDividendsForeignIssuer'] = async (request: Types.OperationsServiceGetDividendsForeignIssuerRequest): Promise<Types.OperationsServiceGetDividendsForeignIssuerResponses> => {
  return await _operationsServiceGetDividendsForeignIssuer(baseUrl, request)
}
const _operationsServiceGetOperations = async (url: string, request: Types.OperationsServiceGetOperationsRequest): Promise<Types.OperationsServiceGetOperationsResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.OperationsService/GetOperations`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const operationsServiceGetOperations: GeneratedApi['operationsServiceGetOperations'] = async (request: Types.OperationsServiceGetOperationsRequest): Promise<Types.OperationsServiceGetOperationsResponses> => {
  return await _operationsServiceGetOperations(baseUrl, request)
}
const _operationsServiceGetOperationsByCursor = async (url: string, request: Types.OperationsServiceGetOperationsByCursorRequest): Promise<Types.OperationsServiceGetOperationsByCursorResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.OperationsService/GetOperationsByCursor`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const operationsServiceGetOperationsByCursor: GeneratedApi['operationsServiceGetOperationsByCursor'] = async (request: Types.OperationsServiceGetOperationsByCursorRequest): Promise<Types.OperationsServiceGetOperationsByCursorResponses> => {
  return await _operationsServiceGetOperationsByCursor(baseUrl, request)
}
const _operationsServiceGetPortfolio = async (url: string, request: Types.OperationsServiceGetPortfolioRequest): Promise<Types.OperationsServiceGetPortfolioResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.OperationsService/GetPortfolio`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const operationsServiceGetPortfolio: GeneratedApi['operationsServiceGetPortfolio'] = async (request: Types.OperationsServiceGetPortfolioRequest): Promise<Types.OperationsServiceGetPortfolioResponses> => {
  return await _operationsServiceGetPortfolio(baseUrl, request)
}
const _operationsServiceGetPositions = async (url: string, request: Types.OperationsServiceGetPositionsRequest): Promise<Types.OperationsServiceGetPositionsResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.OperationsService/GetPositions`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const operationsServiceGetPositions: GeneratedApi['operationsServiceGetPositions'] = async (request: Types.OperationsServiceGetPositionsRequest): Promise<Types.OperationsServiceGetPositionsResponses> => {
  return await _operationsServiceGetPositions(baseUrl, request)
}
const _operationsServiceGetWithdrawLimits = async (url: string, request: Types.OperationsServiceGetWithdrawLimitsRequest): Promise<Types.OperationsServiceGetWithdrawLimitsResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.OperationsService/GetWithdrawLimits`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const operationsServiceGetWithdrawLimits: GeneratedApi['operationsServiceGetWithdrawLimits'] = async (request: Types.OperationsServiceGetWithdrawLimitsRequest): Promise<Types.OperationsServiceGetWithdrawLimitsResponses> => {
  return await _operationsServiceGetWithdrawLimits(baseUrl, request)
}
const _operationsStreamServicePortfolioStream = async (url: string, request: Types.OperationsStreamServicePortfolioStreamRequest): Promise<Types.OperationsStreamServicePortfolioStreamResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.OperationsStreamService/PortfolioStream`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const operationsStreamServicePortfolioStream: GeneratedApi['operationsStreamServicePortfolioStream'] = async (request: Types.OperationsStreamServicePortfolioStreamRequest): Promise<Types.OperationsStreamServicePortfolioStreamResponses> => {
  return await _operationsStreamServicePortfolioStream(baseUrl, request)
}
const _operationsStreamServicePositionsStream = async (url: string, request: Types.OperationsStreamServicePositionsStreamRequest): Promise<Types.OperationsStreamServicePositionsStreamResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.OperationsStreamService/PositionsStream`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const operationsStreamServicePositionsStream: GeneratedApi['operationsStreamServicePositionsStream'] = async (request: Types.OperationsStreamServicePositionsStreamRequest): Promise<Types.OperationsStreamServicePositionsStreamResponses> => {
  return await _operationsStreamServicePositionsStream(baseUrl, request)
}
const _ordersServiceCancelOrder = async (url: string, request: Types.OrdersServiceCancelOrderRequest): Promise<Types.OrdersServiceCancelOrderResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.OrdersService/CancelOrder`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const ordersServiceCancelOrder: GeneratedApi['ordersServiceCancelOrder'] = async (request: Types.OrdersServiceCancelOrderRequest): Promise<Types.OrdersServiceCancelOrderResponses> => {
  return await _ordersServiceCancelOrder(baseUrl, request)
}
const _ordersServiceGetOrderState = async (url: string, request: Types.OrdersServiceGetOrderStateRequest): Promise<Types.OrdersServiceGetOrderStateResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.OrdersService/GetOrderState`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const ordersServiceGetOrderState: GeneratedApi['ordersServiceGetOrderState'] = async (request: Types.OrdersServiceGetOrderStateRequest): Promise<Types.OrdersServiceGetOrderStateResponses> => {
  return await _ordersServiceGetOrderState(baseUrl, request)
}
const _ordersServiceGetOrders = async (url: string, request: Types.OrdersServiceGetOrdersRequest): Promise<Types.OrdersServiceGetOrdersResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.OrdersService/GetOrders`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const ordersServiceGetOrders: GeneratedApi['ordersServiceGetOrders'] = async (request: Types.OrdersServiceGetOrdersRequest): Promise<Types.OrdersServiceGetOrdersResponses> => {
  return await _ordersServiceGetOrders(baseUrl, request)
}
const _ordersServicePostOrder = async (url: string, request: Types.OrdersServicePostOrderRequest): Promise<Types.OrdersServicePostOrderResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.OrdersService/PostOrder`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const ordersServicePostOrder: GeneratedApi['ordersServicePostOrder'] = async (request: Types.OrdersServicePostOrderRequest): Promise<Types.OrdersServicePostOrderResponses> => {
  return await _ordersServicePostOrder(baseUrl, request)
}
const _ordersServiceReplaceOrder = async (url: string, request: Types.OrdersServiceReplaceOrderRequest): Promise<Types.OrdersServiceReplaceOrderResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.OrdersService/ReplaceOrder`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const ordersServiceReplaceOrder: GeneratedApi['ordersServiceReplaceOrder'] = async (request: Types.OrdersServiceReplaceOrderRequest): Promise<Types.OrdersServiceReplaceOrderResponses> => {
  return await _ordersServiceReplaceOrder(baseUrl, request)
}
const _ordersStreamServiceTradesStream = async (url: string, request: Types.OrdersStreamServiceTradesStreamRequest): Promise<Types.OrdersStreamServiceTradesStreamResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.OrdersStreamService/TradesStream`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const ordersStreamServiceTradesStream: GeneratedApi['ordersStreamServiceTradesStream'] = async (request: Types.OrdersStreamServiceTradesStreamRequest): Promise<Types.OrdersStreamServiceTradesStreamResponses> => {
  return await _ordersStreamServiceTradesStream(baseUrl, request)
}
const _sandboxServiceCancelSandboxOrder = async (url: string, request: Types.SandboxServiceCancelSandboxOrderRequest): Promise<Types.SandboxServiceCancelSandboxOrderResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.SandboxService/CancelSandboxOrder`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const sandboxServiceCancelSandboxOrder: GeneratedApi['sandboxServiceCancelSandboxOrder'] = async (request: Types.SandboxServiceCancelSandboxOrderRequest): Promise<Types.SandboxServiceCancelSandboxOrderResponses> => {
  return await _sandboxServiceCancelSandboxOrder(baseUrl, request)
}
const _sandboxServiceCloseSandboxAccount = async (url: string, request: Types.SandboxServiceCloseSandboxAccountRequest): Promise<Types.SandboxServiceCloseSandboxAccountResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.SandboxService/CloseSandboxAccount`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const sandboxServiceCloseSandboxAccount: GeneratedApi['sandboxServiceCloseSandboxAccount'] = async (request: Types.SandboxServiceCloseSandboxAccountRequest): Promise<Types.SandboxServiceCloseSandboxAccountResponses> => {
  return await _sandboxServiceCloseSandboxAccount(baseUrl, request)
}
const _sandboxServiceGetSandboxAccounts = async (url: string, request: Types.SandboxServiceGetSandboxAccountsRequest): Promise<Types.SandboxServiceGetSandboxAccountsResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxAccounts`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const sandboxServiceGetSandboxAccounts: GeneratedApi['sandboxServiceGetSandboxAccounts'] = async (request: Types.SandboxServiceGetSandboxAccountsRequest): Promise<Types.SandboxServiceGetSandboxAccountsResponses> => {
  return await _sandboxServiceGetSandboxAccounts(baseUrl, request)
}
const _sandboxServiceGetSandboxOperations = async (url: string, request: Types.SandboxServiceGetSandboxOperationsRequest): Promise<Types.SandboxServiceGetSandboxOperationsResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxOperations`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const sandboxServiceGetSandboxOperations: GeneratedApi['sandboxServiceGetSandboxOperations'] = async (request: Types.SandboxServiceGetSandboxOperationsRequest): Promise<Types.SandboxServiceGetSandboxOperationsResponses> => {
  return await _sandboxServiceGetSandboxOperations(baseUrl, request)
}
const _sandboxServiceGetSandboxOperationsByCursor = async (url: string, request: Types.SandboxServiceGetSandboxOperationsByCursorRequest): Promise<Types.SandboxServiceGetSandboxOperationsByCursorResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxOperationsByCursor`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const sandboxServiceGetSandboxOperationsByCursor: GeneratedApi['sandboxServiceGetSandboxOperationsByCursor'] = async (request: Types.SandboxServiceGetSandboxOperationsByCursorRequest): Promise<Types.SandboxServiceGetSandboxOperationsByCursorResponses> => {
  return await _sandboxServiceGetSandboxOperationsByCursor(baseUrl, request)
}
const _sandboxServiceGetSandboxOrderState = async (url: string, request: Types.SandboxServiceGetSandboxOrderStateRequest): Promise<Types.SandboxServiceGetSandboxOrderStateResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxOrderState`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const sandboxServiceGetSandboxOrderState: GeneratedApi['sandboxServiceGetSandboxOrderState'] = async (request: Types.SandboxServiceGetSandboxOrderStateRequest): Promise<Types.SandboxServiceGetSandboxOrderStateResponses> => {
  return await _sandboxServiceGetSandboxOrderState(baseUrl, request)
}
const _sandboxServiceGetSandboxOrders = async (url: string, request: Types.SandboxServiceGetSandboxOrdersRequest): Promise<Types.SandboxServiceGetSandboxOrdersResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxOrders`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const sandboxServiceGetSandboxOrders: GeneratedApi['sandboxServiceGetSandboxOrders'] = async (request: Types.SandboxServiceGetSandboxOrdersRequest): Promise<Types.SandboxServiceGetSandboxOrdersResponses> => {
  return await _sandboxServiceGetSandboxOrders(baseUrl, request)
}
const _sandboxServiceGetSandboxPortfolio = async (url: string, request: Types.SandboxServiceGetSandboxPortfolioRequest): Promise<Types.SandboxServiceGetSandboxPortfolioResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxPortfolio`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const sandboxServiceGetSandboxPortfolio: GeneratedApi['sandboxServiceGetSandboxPortfolio'] = async (request: Types.SandboxServiceGetSandboxPortfolioRequest): Promise<Types.SandboxServiceGetSandboxPortfolioResponses> => {
  return await _sandboxServiceGetSandboxPortfolio(baseUrl, request)
}
const _sandboxServiceGetSandboxPositions = async (url: string, request: Types.SandboxServiceGetSandboxPositionsRequest): Promise<Types.SandboxServiceGetSandboxPositionsResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxPositions`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const sandboxServiceGetSandboxPositions: GeneratedApi['sandboxServiceGetSandboxPositions'] = async (request: Types.SandboxServiceGetSandboxPositionsRequest): Promise<Types.SandboxServiceGetSandboxPositionsResponses> => {
  return await _sandboxServiceGetSandboxPositions(baseUrl, request)
}
const _sandboxServiceGetSandboxWithdrawLimits = async (url: string, request: Types.SandboxServiceGetSandboxWithdrawLimitsRequest): Promise<Types.SandboxServiceGetSandboxWithdrawLimitsResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxWithdrawLimits`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const sandboxServiceGetSandboxWithdrawLimits: GeneratedApi['sandboxServiceGetSandboxWithdrawLimits'] = async (request: Types.SandboxServiceGetSandboxWithdrawLimitsRequest): Promise<Types.SandboxServiceGetSandboxWithdrawLimitsResponses> => {
  return await _sandboxServiceGetSandboxWithdrawLimits(baseUrl, request)
}
const _sandboxServiceOpenSandboxAccount = async (url: string, request: Types.SandboxServiceOpenSandboxAccountRequest): Promise<Types.SandboxServiceOpenSandboxAccountResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.SandboxService/OpenSandboxAccount`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const sandboxServiceOpenSandboxAccount: GeneratedApi['sandboxServiceOpenSandboxAccount'] = async (request: Types.SandboxServiceOpenSandboxAccountRequest): Promise<Types.SandboxServiceOpenSandboxAccountResponses> => {
  return await _sandboxServiceOpenSandboxAccount(baseUrl, request)
}
const _sandboxServicePostSandboxOrder = async (url: string, request: Types.SandboxServicePostSandboxOrderRequest): Promise<Types.SandboxServicePostSandboxOrderResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.SandboxService/PostSandboxOrder`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const sandboxServicePostSandboxOrder: GeneratedApi['sandboxServicePostSandboxOrder'] = async (request: Types.SandboxServicePostSandboxOrderRequest): Promise<Types.SandboxServicePostSandboxOrderResponses> => {
  return await _sandboxServicePostSandboxOrder(baseUrl, request)
}
const _sandboxServiceReplaceSandboxOrder = async (url: string, request: Types.SandboxServiceReplaceSandboxOrderRequest): Promise<Types.SandboxServiceReplaceSandboxOrderResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.SandboxService/ReplaceSandboxOrder`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const sandboxServiceReplaceSandboxOrder: GeneratedApi['sandboxServiceReplaceSandboxOrder'] = async (request: Types.SandboxServiceReplaceSandboxOrderRequest): Promise<Types.SandboxServiceReplaceSandboxOrderResponses> => {
  return await _sandboxServiceReplaceSandboxOrder(baseUrl, request)
}
const _sandboxServiceSandboxPayIn = async (url: string, request: Types.SandboxServiceSandboxPayInRequest): Promise<Types.SandboxServiceSandboxPayInResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.SandboxService/SandboxPayIn`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const sandboxServiceSandboxPayIn: GeneratedApi['sandboxServiceSandboxPayIn'] = async (request: Types.SandboxServiceSandboxPayInRequest): Promise<Types.SandboxServiceSandboxPayInResponses> => {
  return await _sandboxServiceSandboxPayIn(baseUrl, request)
}
const _stopOrdersServiceCancelStopOrder = async (url: string, request: Types.StopOrdersServiceCancelStopOrderRequest): Promise<Types.StopOrdersServiceCancelStopOrderResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.StopOrdersService/CancelStopOrder`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const stopOrdersServiceCancelStopOrder: GeneratedApi['stopOrdersServiceCancelStopOrder'] = async (request: Types.StopOrdersServiceCancelStopOrderRequest): Promise<Types.StopOrdersServiceCancelStopOrderResponses> => {
  return await _stopOrdersServiceCancelStopOrder(baseUrl, request)
}
const _stopOrdersServiceGetStopOrders = async (url: string, request: Types.StopOrdersServiceGetStopOrdersRequest): Promise<Types.StopOrdersServiceGetStopOrdersResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.StopOrdersService/GetStopOrders`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const stopOrdersServiceGetStopOrders: GeneratedApi['stopOrdersServiceGetStopOrders'] = async (request: Types.StopOrdersServiceGetStopOrdersRequest): Promise<Types.StopOrdersServiceGetStopOrdersResponses> => {
  return await _stopOrdersServiceGetStopOrders(baseUrl, request)
}
const _stopOrdersServicePostStopOrder = async (url: string, request: Types.StopOrdersServicePostStopOrderRequest): Promise<Types.StopOrdersServicePostStopOrderResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.StopOrdersService/PostStopOrder`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const stopOrdersServicePostStopOrder: GeneratedApi['stopOrdersServicePostStopOrder'] = async (request: Types.StopOrdersServicePostStopOrderRequest): Promise<Types.StopOrdersServicePostStopOrderResponses> => {
  return await _stopOrdersServicePostStopOrder(baseUrl, request)
}
const _usersServiceGetAccounts = async (url: string, request: Types.UsersServiceGetAccountsRequest): Promise<Types.UsersServiceGetAccountsResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.UsersService/GetAccounts`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const usersServiceGetAccounts: GeneratedApi['usersServiceGetAccounts'] = async (request: Types.UsersServiceGetAccountsRequest): Promise<Types.UsersServiceGetAccountsResponses> => {
  return await _usersServiceGetAccounts(baseUrl, request)
}
const _usersServiceGetInfo = async (url: string, request: Types.UsersServiceGetInfoRequest): Promise<Types.UsersServiceGetInfoResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.UsersService/GetInfo`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const usersServiceGetInfo: GeneratedApi['usersServiceGetInfo'] = async (request: Types.UsersServiceGetInfoRequest): Promise<Types.UsersServiceGetInfoResponses> => {
  return await _usersServiceGetInfo(baseUrl, request)
}
const _usersServiceGetMarginAttributes = async (url: string, request: Types.UsersServiceGetMarginAttributesRequest): Promise<Types.UsersServiceGetMarginAttributesResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.UsersService/GetMarginAttributes`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const usersServiceGetMarginAttributes: GeneratedApi['usersServiceGetMarginAttributes'] = async (request: Types.UsersServiceGetMarginAttributesRequest): Promise<Types.UsersServiceGetMarginAttributesResponses> => {
  return await _usersServiceGetMarginAttributes(baseUrl, request)
}
const _usersServiceGetUserTariff = async (url: string, request: Types.UsersServiceGetUserTariffRequest): Promise<Types.UsersServiceGetUserTariffResponses> => {
  const body = request
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/tinkoff.public.invest.api.contract.v1.UsersService/GetUserTariff`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  if (!response.ok) {
    throw new Error(await response.text())
  }

  return await response.json()
}

export const usersServiceGetUserTariff: GeneratedApi['usersServiceGetUserTariff'] = async (request: Types.UsersServiceGetUserTariffRequest): Promise<Types.UsersServiceGetUserTariffResponses> => {
  return await _usersServiceGetUserTariff(baseUrl, request)
}
type BuildOptions = {
  headers?: object
}
export default function build (url: string, options?: BuildOptions) {
  url = sanitizeUrl(url)
  if (options?.headers) {
    defaultHeaders = options.headers
  }
  return {
    instrumentsServiceBondBy: _instrumentsServiceBondBy.bind(url, ...arguments),
    instrumentsServiceBonds: _instrumentsServiceBonds.bind(url, ...arguments),
    instrumentsServiceCurrencies: _instrumentsServiceCurrencies.bind(url, ...arguments),
    instrumentsServiceCurrencyBy: _instrumentsServiceCurrencyBy.bind(url, ...arguments),
    instrumentsServiceEditFavorites: _instrumentsServiceEditFavorites.bind(url, ...arguments),
    instrumentsServiceEtfBy: _instrumentsServiceEtfBy.bind(url, ...arguments),
    instrumentsServiceEtfs: _instrumentsServiceEtfs.bind(url, ...arguments),
    instrumentsServiceFindInstrument: _instrumentsServiceFindInstrument.bind(url, ...arguments),
    instrumentsServiceFutureBy: _instrumentsServiceFutureBy.bind(url, ...arguments),
    instrumentsServiceFutures: _instrumentsServiceFutures.bind(url, ...arguments),
    instrumentsServiceGetAccruedInterests: _instrumentsServiceGetAccruedInterests.bind(url, ...arguments),
    instrumentsServiceGetAssetBy: _instrumentsServiceGetAssetBy.bind(url, ...arguments),
    instrumentsServiceGetAssets: _instrumentsServiceGetAssets.bind(url, ...arguments),
    instrumentsServiceGetBondCoupons: _instrumentsServiceGetBondCoupons.bind(url, ...arguments),
    instrumentsServiceGetBrandBy: _instrumentsServiceGetBrandBy.bind(url, ...arguments),
    instrumentsServiceGetBrands: _instrumentsServiceGetBrands.bind(url, ...arguments),
    instrumentsServiceGetCountries: _instrumentsServiceGetCountries.bind(url, ...arguments),
    instrumentsServiceGetDividends: _instrumentsServiceGetDividends.bind(url, ...arguments),
    instrumentsServiceGetFavorites: _instrumentsServiceGetFavorites.bind(url, ...arguments),
    instrumentsServiceGetFuturesMargin: _instrumentsServiceGetFuturesMargin.bind(url, ...arguments),
    instrumentsServiceGetInstrumentBy: _instrumentsServiceGetInstrumentBy.bind(url, ...arguments),
    instrumentsServiceOptionBy: _instrumentsServiceOptionBy.bind(url, ...arguments),
    instrumentsServiceOptions: _instrumentsServiceOptions.bind(url, ...arguments),
    instrumentsServiceOptionsBy: _instrumentsServiceOptionsBy.bind(url, ...arguments),
    instrumentsServiceShareBy: _instrumentsServiceShareBy.bind(url, ...arguments),
    instrumentsServiceShares: _instrumentsServiceShares.bind(url, ...arguments),
    instrumentsServiceTradingSchedules: _instrumentsServiceTradingSchedules.bind(url, ...arguments),
    marketDataServiceGetCandles: _marketDataServiceGetCandles.bind(url, ...arguments),
    marketDataServiceGetClosePrices: _marketDataServiceGetClosePrices.bind(url, ...arguments),
    marketDataServiceGetLastPrices: _marketDataServiceGetLastPrices.bind(url, ...arguments),
    marketDataServiceGetLastTrades: _marketDataServiceGetLastTrades.bind(url, ...arguments),
    marketDataServiceGetOrderBook: _marketDataServiceGetOrderBook.bind(url, ...arguments),
    marketDataServiceGetTradingStatus: _marketDataServiceGetTradingStatus.bind(url, ...arguments),
    marketDataServiceGetTradingStatuses: _marketDataServiceGetTradingStatuses.bind(url, ...arguments),
    marketDataStreamServiceMarketDataServerSideStream: _marketDataStreamServiceMarketDataServerSideStream.bind(url, ...arguments),
    marketDataStreamServiceMarketDataStream: _marketDataStreamServiceMarketDataStream.bind(url, ...arguments),
    operationsServiceGetBrokerReport: _operationsServiceGetBrokerReport.bind(url, ...arguments),
    operationsServiceGetDividendsForeignIssuer: _operationsServiceGetDividendsForeignIssuer.bind(url, ...arguments),
    operationsServiceGetOperations: _operationsServiceGetOperations.bind(url, ...arguments),
    operationsServiceGetOperationsByCursor: _operationsServiceGetOperationsByCursor.bind(url, ...arguments),
    operationsServiceGetPortfolio: _operationsServiceGetPortfolio.bind(url, ...arguments),
    operationsServiceGetPositions: _operationsServiceGetPositions.bind(url, ...arguments),
    operationsServiceGetWithdrawLimits: _operationsServiceGetWithdrawLimits.bind(url, ...arguments),
    operationsStreamServicePortfolioStream: _operationsStreamServicePortfolioStream.bind(url, ...arguments),
    operationsStreamServicePositionsStream: _operationsStreamServicePositionsStream.bind(url, ...arguments),
    ordersServiceCancelOrder: _ordersServiceCancelOrder.bind(url, ...arguments),
    ordersServiceGetOrderState: _ordersServiceGetOrderState.bind(url, ...arguments),
    ordersServiceGetOrders: _ordersServiceGetOrders.bind(url, ...arguments),
    ordersServicePostOrder: _ordersServicePostOrder.bind(url, ...arguments),
    ordersServiceReplaceOrder: _ordersServiceReplaceOrder.bind(url, ...arguments),
    ordersStreamServiceTradesStream: _ordersStreamServiceTradesStream.bind(url, ...arguments),
    sandboxServiceCancelSandboxOrder: _sandboxServiceCancelSandboxOrder.bind(url, ...arguments),
    sandboxServiceCloseSandboxAccount: _sandboxServiceCloseSandboxAccount.bind(url, ...arguments),
    sandboxServiceGetSandboxAccounts: _sandboxServiceGetSandboxAccounts.bind(url, ...arguments),
    sandboxServiceGetSandboxOperations: _sandboxServiceGetSandboxOperations.bind(url, ...arguments),
    sandboxServiceGetSandboxOperationsByCursor: _sandboxServiceGetSandboxOperationsByCursor.bind(url, ...arguments),
    sandboxServiceGetSandboxOrderState: _sandboxServiceGetSandboxOrderState.bind(url, ...arguments),
    sandboxServiceGetSandboxOrders: _sandboxServiceGetSandboxOrders.bind(url, ...arguments),
    sandboxServiceGetSandboxPortfolio: _sandboxServiceGetSandboxPortfolio.bind(url, ...arguments),
    sandboxServiceGetSandboxPositions: _sandboxServiceGetSandboxPositions.bind(url, ...arguments),
    sandboxServiceGetSandboxWithdrawLimits: _sandboxServiceGetSandboxWithdrawLimits.bind(url, ...arguments),
    sandboxServiceOpenSandboxAccount: _sandboxServiceOpenSandboxAccount.bind(url, ...arguments),
    sandboxServicePostSandboxOrder: _sandboxServicePostSandboxOrder.bind(url, ...arguments),
    sandboxServiceReplaceSandboxOrder: _sandboxServiceReplaceSandboxOrder.bind(url, ...arguments),
    sandboxServiceSandboxPayIn: _sandboxServiceSandboxPayIn.bind(url, ...arguments),
    stopOrdersServiceCancelStopOrder: _stopOrdersServiceCancelStopOrder.bind(url, ...arguments),
    stopOrdersServiceGetStopOrders: _stopOrdersServiceGetStopOrders.bind(url, ...arguments),
    stopOrdersServicePostStopOrder: _stopOrdersServicePostStopOrder.bind(url, ...arguments),
    usersServiceGetAccounts: _usersServiceGetAccounts.bind(url, ...arguments),
    usersServiceGetInfo: _usersServiceGetInfo.bind(url, ...arguments),
    usersServiceGetMarginAttributes: _usersServiceGetMarginAttributes.bind(url, ...arguments),
    usersServiceGetUserTariff: _usersServiceGetUserTariff.bind(url, ...arguments)
  }
}