// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.19.1

/* eslint-disable */

export * as tpublic from "./index.tinkoff.public";
